// @ts-nocheck
function toolWebhookSetupHint() {
  return {
    name: "webhook.setup_hint",
    description: "Print webhook verification/setup instructions for Meta developers portal.",
    risk: "low",
    async execute(ctx, args) {
      const url = args?.url;
      const verifyToken = ctx.config?.webhookVerifyToken;
      if (!url) throw new Error("Missing `url`.");
      if (!verifyToken) throw new Error("Missing webhook verify token. Run `waba webhook setup --url ...` first.");

      const normalized = String(url).replace(/\/+$/, "");
      const callback = `${normalized}/webhook`;
      return {
        ok: true,
        callbackUrl: callback,
        verifyTokenHint: "***stored in config***",
        instructions:
          "Meta setup:\n" +
          `- Callback URL: ${callback}\n` +
          "- Verify token: use the one generated by this CLI\n" +
          "- Subscribe to: messages, message_status (and any others you need)\n" +
          "- (Optional) Enable signature verification by setting WABA_APP_SECRET"
      };
    }
  };
}

module.exports = { toolWebhookSetupHint };

